# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: 'v1.0'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'dockerarnaud'
        repository: 'moucheron/webdriver'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: 'v1.0'
        addPipelineData: false